CREATE TABLE IF NOT EXISTS public.full_posts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying COLLATE pg_catalog."default" NOT NULL,
    body character varying COLLATE pg_catalog."default" NOT NULL,
    url character varying COLLATE pg_catalog."default" NOT NULL,
    post_id integer,
    CONSTRAINT full_posts_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.full_posts
    OWNER to postgres;